server:
  port: 8082
spring:
  application:
    name: demo
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://120.25.167.218:5432/mybatisplusdemo?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
  profiles:
    active: dev
